version: 2

# conda:
#   environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - nodejs
    - npm
    - libglx-mesa0
    - libgl1
    - xvfb
  commands:
    - conda env create --name festim-workshop-jupyter2 --file environment.yml
    - cd book
    - conda run -n festim-workshop-jupyter2 python -m jupyter book build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r book/_build/html/* $READTHEDOCS_OUTPUT/html/