version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"

conda:
  environment: environment.yml

sphinx:
  builder: html
  fail_on_warning: true
  configuration: book/_config.yml