version: 2

# conda:
#   environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - libglx-mesa0
    - libgl1
    - xvfb
  commands:
    - conda env create --name festim-workshop-jupyter2 --file environment.yml
    - conda init
    - conda activate festim-workshop-jupyter2

    - cd book
    - python -m jupyter_book build --html .
    - cp -r _build/html/* $READTHEDOCS_OUTPUT/html/