version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - libglx-mesa0
    - libgl1
    - xvfb
  commands:
  # this may need the --execute flag to run the notebooks
    - cd book && jupyter book build --html

conda:
  environment: environment.yml

formats: []
