#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PathSim Simulation
==================

Generated by PathView on 2026-01-28 13:42:20
https://view.pathsim.org

PathSim documentation: https://docs.pathsim.org
"""

# ────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ────────────────────────────────────────────────────────────────────────────

import numpy as np
import matplotlib.pyplot as plt

from pathsim import Simulation, Connection
from pathsim.blocks import Adder, Amplifier, Integrator, PulseSource, Scope
from pathsim_chem.tritium import Process, Splitter
from pathsim.solvers import RKBS32

# ────────────────────────────────────────────────────────────────────────────
# USER-DEFINED CODE
# ────────────────────────────────────────────────────────────────────────────

fusion_power = 525  # MWth
tritium_burn_rate = 9.3e-7  # kg/s
pulse_duration = 1800  # s
time_between_pulses = 60  # s
TBE = 0.02
non_rad_loss_fraction = 1e-4
AF = 0.7
tritium_processing_time = 4 * 3600  # s
frac_dir = 0.3
frac_iss_det = 0.1

tau_blanket = 1.25 * 3600  # s
tau_fw = 1000  # s
tau_divertor = 1000  # s
tau_tes = 24 * 3600  # s
tau_hx = 1000  # s
tau_vacuum_pump = 600  # s
tau_fuel_cleanup = 0.3 * 3600  # s
tau_iss = 3 * 3600  # s
tau_detritiation = 1 * 3600  # s
tau_membrane = 100  # s

f_p3 = 1e-4
f_p4 = 1e-4

TBR = 1.05
tes_efficiency = 0.95
startup_inventory = 1.14

# ────────────────────────────────────────────────────────────────────────────
# BLOCKS
# ────────────────────────────────────────────────────────────────────────────

# Sources
fusionrate = PulseSource(
    T=pulse_duration,
    amplitude=tritium_burn_rate,
    duty=AF,
    t_rise=pulse_duration * 0.01,
    t_fall=pulse_duration * 0.01,
)

# Dynamic
storage = Integrator(initial_value=startup_inventory)

# Algebraic
plasmadiv = Amplifier(gain=f_p4 / TBE)
plasmafw_ = Amplifier(gain=f_p3 / TBE)
tbr = Amplifier(gain=TBR)
injectionrate = Amplifier(gain=-1 / TBE)
pumpingrate = Amplifier(gain=(1 - TBE - f_p3 - f_p4) / TBE)
totalflux = Adder()
primaryflux = Adder()

# Recording
block_9 = Scope()
scopestorage = Scope()
scopeblanket = Scope()
scopetes = Scope()
scopehe = Scope()
scopefw = Scope()
scopediv = Scope()
scopepump__ = Scope()
scopefc = Scope()
scopeiss = Scope()
scopeprimaryflux = Scope()
scopetsep = Scope()

# Chemical
divertor = Process(tau=tau_divertor)
fw = Process(tau=tau_fw)
blanket = Process(tau=tau_blanket)
tsepmem = Process(tau=tau_membrane)
tes = Process(tau=tau_tes)
heatexchanger = Process(tau=tau_hx)
pump = Process(tau=tau_vacuum_pump)
fuelcleanup = Process(tau=tau_fuel_cleanup)
iss = Process(tau=tau_iss)
detritiation = Process(tau=tau_detritiation)
splittertsephx = Splitter(fractions=[tes_efficiency, 1 - tes_efficiency])
splitterpump = Splitter(fractions=[1 - frac_dir, frac_dir])
splitteriss = Splitter(fractions=[frac_iss_det, 1 - frac_iss_det])
splitterhx = Splitter(fractions=[1 / 3, 1 / 3, 1 / 3])

blocks = [
    fusionrate,
    storage,
    plasmadiv,
    plasmafw_,
    tbr,
    injectionrate,
    pumpingrate,
    totalflux,
    primaryflux,
    block_9,
    scopestorage,
    scopeblanket,
    scopetes,
    scopehe,
    scopefw,
    scopediv,
    scopepump__,
    scopefc,
    scopeiss,
    scopeprimaryflux,
    scopetsep,
    divertor,
    fw,
    blanket,
    tsepmem,
    tes,
    heatexchanger,
    pump,
    fuelcleanup,
    iss,
    detritiation,
    splittertsephx,
    splitterpump,
    splitteriss,
    splitterhx,
]

# ────────────────────────────────────────────────────────────────────────────
# CONNECTIONS
# ────────────────────────────────────────────────────────────────────────────

connections = [
    Connection(
        fusionrate[0],
        plasmadiv[0],
        plasmafw_[0],
        tbr[0],
        injectionrate[0],
        pumpingrate[0],
        block_9[0],
    ),
    Connection(plasmadiv[0], divertor[0]),
    Connection(plasmafw_[0], fw[0]),
    Connection(tbr[0], blanket[0]),
    Connection(fw[1], blanket[1]),
    Connection(divertor[1], blanket[2]),
    Connection(blanket[1], tes[0]),
    Connection(pumpingrate[0], pump[0]),
    Connection(fuelcleanup[1], iss[0]),
    Connection(detritiation[1], iss[1]),
    Connection(totalflux[0], storage[0]),
    Connection(splittertsephx[1], heatexchanger[0]),
    Connection(splittertsephx[0], tsepmem[0]),
    Connection(tes[1], splittertsephx[0]),
    Connection(pump[1], splitterpump[0]),
    Connection(iss[1], splitteriss[0]),
    Connection(storage[0], scopestorage[0]),
    Connection(splitterpump[0], fuelcleanup[0]),
    Connection(splitteriss[0], detritiation[0]),
    Connection(blanket[0], scopeblanket[0]),
    Connection(tes[0], scopetes[0]),
    Connection(heatexchanger[0], scopehe[0]),
    Connection(fw[0], scopefw[0]),
    Connection(divertor[0], scopediv[0]),
    Connection(pump[0], scopepump__[0]),
    Connection(fuelcleanup[0], scopefc[0]),
    Connection(iss[0], scopeiss[0]),
    Connection(splitterpump[1], primaryflux[1]),
    Connection(tsepmem[1], totalflux[2]),
    Connection(injectionrate[0], totalflux[1]),
    Connection(primaryflux[0], totalflux[0], scopeprimaryflux[0]),
    Connection(tsepmem[0], scopetsep[0]),
    Connection(splitteriss[1], primaryflux[0]),
    Connection(heatexchanger[1], splitterhx[0]),
    Connection(splitterhx[0], blanket[3]),
    Connection(splitterhx[1], fw[1]),
    Connection(splitterhx[2], divertor[1]),
]

# ────────────────────────────────────────────────────────────────────────────
# SIMULATION
# ────────────────────────────────────────────────────────────────────────────

sim = Simulation(
    blocks,
    connections,
    Solver=RKBS32,
    dt=100,
    dt_min=1e-16,
    tolerance_lte_rel=1e-3,
    tolerance_lte_abs=1e-5,
    tolerance_fpi=1e-10,
)

# ────────────────────────────────────────────────────────────────────────────
# MAIN
# ────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Run simulation
    sim.run(duration=100 * 24 * 3600)

    # Plot results
    sim.plot()
    plt.show()
