name: festim-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-book
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - matplotlib
  - meshio[all]
  - pip>=20.1
  - pyvista
  - ipykernel
  - nbconvert
  - fenics-dolfinx
  - festim=2.0a2
  - pip:
    - pyparsing
    - h-transport-materials==0.16
    - pyvista[all,trame]  # trame cannot be installed on conda