name: festim-workshop
channels:
  - conda-forge
  - defaults

dependencies:
  - python<3.14
  - pip=23.3
  - setuptools<82
  - wheel<0.45
  - jupyter-book<2.0
  - jupytext
  - ipykernel
  - nbconvert
  - sphinx-tags
  - matplotlib
  - scipy
  - shapely
  - meshio
  - fenics-dolfinx
  - python-gmsh
  - festim=2.0b1
  - pip:
      - h-transport-materials==0.16
      - pyparsing
      - pyvista[all,trame]<0.47.0
