# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FESTIM tutorial
author: The FESTIM community



# Information about where the book exists on the web
repository:
  url: https://github.com/festim-dev/FESTIM-workshop  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

execute:
  # Force re-execution of notebooks on each build.
  # See https://jupyterbook.org/content/execute.html
  # execute_notebooks: force
  timeout: -1  # Disable timeouts for executing notebooks cells
  # allow_errors: true  # Allow errors in notebook cells

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true