# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FESTIM tutorial
author: The FESTIM community

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/festim-dev/FESTIM-workshop  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
